language: generic
env:
  global:
    # Set defaults to avoid repeating in most cases
    - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - NUMPY_VERSION=stable
    - MAIN_CMD='python setup.py'
    - CONDA_DEPENDENCIES='xarray dask toolz Cython sphinx cartopy pillow matplotlib scipy pyyaml pyproj pyresample coveralls coverage codecov behave netcdf4 h5py h5netcdf gdal rasterio imageio pyhdf mock libtiff sphinx-argparse graphviz python-graphviz pycoast'
    - PIP_DEPENDENCIES='trollsift trollimage pyspectral pyorbital libtiff'
    - SETUP_XVFB=False
    - EVENT_TYPE='push pull_request'
    - SETUP_CMD='test'
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
install:
  - wget ftp://128.104.108.86/pub/CSPP/p2g_v_2_1_examples/amsr2/images_basic/gcom-w1_amsr2_btemp_36.5h_20160719_190300_wgs84_fit.jpg
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install git+https://github.com/pytroll/satpy.git
  - pip install -e .
script:
  - python -m polar2grid.tests && cd doc && make html
#  make clean
#  make latexpdf
#after_success:
#- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; codecov; fi
#deploy:
#  - provider: pypi
#    user: dhoese
#    password:
#      secure: frK+0k1STeTM7SizRseP0qdTfOVz9ZMIra+3qEytPdxCLceXAH8LxPU16zj5rdNQxasF1hZ6rAd952fly+ypw2TEf5r2WnStrt7G5QlyE7VB6XGSDpIUxKF1FYccLvYs0/R6Y35MTEPqdM51PM5yEBjoY5b4tA3RF3fDq11cqc/SiWr6DgSLB1WJZULOdtCzBbfGbm5LyJ7yeNbISASSAwVvZTGWw7kJDgi0W5zxwEX82N5tBGbfKIu59qmxyj8FxmcrUwKZ4P3rQNg1kN1utzAB+PSf3GAVvbZfWJQuAKwMqpZgaV9lX0V7eUd/AxPobzEk9WyoNBMIdrSPej5BKWTDiYvaeRTOsggoUCSQJJA/SITEvkJgLWXoKKX2OWrM8RBUO4MoZJpPGXN42PRtMJkV2sx6ZigkpJlHdn39SsIRZX31zsfv8bBhclb70bt1Ts0fDd0rVdZAI6gMI+sgUePwEUn+XbWrvI0sMfDX3QsXDMV393RHgaIPxd+lRqUlYsNOxjsWpsbsvX55ePLxYHsNrv11KKyL/iGjGotVeVUO5D78qvfd4JrsUnMalQyZfW8NTEKa5Ebcs7gYJTwYEOTCQU12BkHOv1zFkjZG5RdGwkEvG3pykLhx+qDyYEd7pKB3TvhzLPqZPSrPxirwcoc0UzCc6ocYdzpqVuViFuk=
#    distributions: sdist bdist_wheel
#    skip_existing: true
#    on:
#      tags: true
#      repo: pytroll/satpy

