name: jenkins_p2g_swbundle
channels:
  - conda-forge
dependencies:
  - aggdraw
  - appdirs
  - cftime
  - conda-pack
  - configobj
  - curl
  - dask
  - distributed
  - ffmpeg
  - fontconfig
  - freetype
  - gdal
  - h5py
  - netcdf4
  - pillow
  - pip
  - pycoast
  - pydecorate
  - pyhdf
  - pykdtree
  - pyorbital
  - pyproj
  - pyresample>=1.18.1
  - pyshp
  - pyspectral
  - python=3.8
  - python-geotiepoints
  - pyyaml
  - rasterio
  - requests
  - setuptools
  - six
  - trollimage>=1.15.0
  - trollsift
  - scipy
  - zarr
  - xarray
  - pip:
    - git+https://github.com/pytroll/satpy.git
