name: jenkins_p2g_swbundle
channels:
  - conda-forge
dependencies:
  - aggdraw
  - appdirs
  - cftime
  - conda-pack
  - configobj
  - curl
  - dask>=2023.9.0
  - distributed>=2023.9.0
  - donfig>=0.8.1
  - ffmpeg
  - fontconfig
  - freetype
  - gdal
  - h5py
  - netcdf4
  - pillow
  - pip
  - pooch
  - pycoast>=1.6.1
  - pydecorate>=0.3.4
  - pyhdf
  - pykdtree
  - pyorbital>=1.8.0
  - pyproj>=3.1.0
  - pyresample>=1.27.1
  - pyshp
  - pyspectral>=0.12.3
  - python=3.11
  - python-geotiepoints>=1.6.0
  - pyyaml
  - rasterio>=1.2.10
  - requests
  - setuptools
  - six
  - trollimage>=1.21.0
  - trollsift>=0.5.0
  - scipy
  - zarr
  - xarray>=2023.8.0
  - fsspec
  - s3fs
  - pip:
    - git+https://github.com/pytroll/satpy.git
