name: test
channels:
  - conda-forge
dependencies:
  - aggdraw
  - appdirs
  - cftime
  - configobj
  - curl
  - dask
  - distributed
  - ffmpeg
  - fontconfig
  - freetype
  - gdal
  - h5py
  - matplotlib
  - netcdf4
  - pillow
  - pycoast
  - pydecorate
  - pyhdf
  - pykdtree
  - pyorbital
  - pyproj
  - pyshp
  - pyspectral
  - python=3.11
  - python-geotiepoints
  - pyyaml
  - rasterio
  - requests
  - setuptools
  - six
  - trollimage
  - trollsift
  - scipy
  - zarr
  - xarray
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - sphinx
  - pip
  - python-graphviz
  - sphinx-argparse
  - fsspec
  - s3fs
  - sphinxcontrib-apidoc
  - pip:
      - git+https://github.com/pytroll/satpy.git
      - git+https://github.com/pytroll/pyresample.git
